openapi: 3.0.3
info:
  title: HFDLSP API
  version: 1.0.0
  description: The official API documentation for HFDLSP.
paths:
  /answer/:
    get:
      operationId: answer_retrieve
      description: Get an answer to a question from a dataset.
      parameters:
      - in: query
        name: dataset
        schema:
          type: string
        description: The ID of the dataset to query as specified in the app.
        required: true
        examples:
          Example1:
            value: tree_of_knowledge
            summary: Example 1
      - in: query
        name: query
        schema:
          type: string
        description: The query/question you want to get an answer to.
        required: true
        examples:
          Example1:
            value: explain chemistry
            summary: Example 1
      tags:
      - answer
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  result:
                    type: string
                    description: The string containing the answer to the query.
          description: ''
        '500':
          content:
            application/json:
              schema:
                properties:
                  error:
                    type: string
                    description: The error that occured while trying to fetch the
                      answer to the query.
          description: ''
        '400':
          content:
            application/json:
              schema:
                properties:
                  error:
                    type: string
                    description: The error that occured as a result of a bad input.
          description: ''
  /fetch_dataset/:
    get:
      operationId: fetch_dataset_retrieve
      parameters:
      - in: query
        name: dataset
        schema:
          type: string
        description: The ID of the dataset to import from HuggingFace to the Neo4j
          database.
        required: true
        examples:
          Example1:
            value: tree_of_knowledge
            summary: Example 1
      tags:
      - fetch_dataset
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  result:
                    type: string
                    description: A success mesage containing the result of the operation.
          description: ''
        '500':
          content:
            application/json:
              schema:
                properties:
                  error:
                    type: string
                    description: The error that occured while trying to import the
                      dataset.
          description: ''
        '400':
          content:
            application/json:
              schema:
                properties:
                  error:
                    type: string
                    description: The error that occured as a result of an invalid
                      dataset ID.
          description: ''
  /schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
